### ISSUE TITLE
Control LED to show if webcam is streaming

### ISSUE THREAD

**Issue by dgsiegel** [peterbay/uvc-gadget#2]
It would be amazing if we could bind the LED to uvc-gadget and activate it, when it actually is recording/streaming.

You can control it like described here: https://www.raspberrypi.org/forums/viewtopic.php?p=136266&sid=26a616050c88a6a82dbe4540de2fb498#p136266

**Comment by peterbay** [comment]
The feature was added - [commit](https://github.com/peterbay/uvc-gadget/commit/bf1b5fba283d1b08f8616a9d3c1567b4eeca9d20)
Added new uvc-gadget argument -p for the setting of the pin number.

**Comment by dgsiegel** [comment]
I could only test the on-board led, but that works flawlessly. Thanks!
